name: quickqr_scanner_plugin
description: "Enterprise-grade QR code scanner with Vision framework integration for iOS and ML Kit for Android. High-performance, low-latency scanning with comprehensive error handling."
version: 1.1.0
homepage: https://github.com/ifapmzadu6/quickqr_scanner_plugin
repository: https://github.com/ifapmzadu6/quickqr_scanner_plugin
issue_tracker: https://github.com/ifapmzadu6/quickqr_scanner_plugin/issues
documentation: https://github.com/ifapmzadu6/quickqr_scanner_plugin/wiki
topics:
  - qr-code
  - barcode
  - scanner
  - vision
  - mlkit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.quickqr_scanner
        pluginClass: QuickqrScannerPlugin
      ios:
        pluginClass: QuickqrScannerPlugin